# Generated by Django 4.1.3 on 2022-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_typecategory_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_category',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(default='Common', related_name='relatedwhat3', to='main.sizecategory', verbose_name='SizeCategory'),
        ),
        migrations.AlterField(
            model_name='sizecategory',
            name='size',
            field=models.CharField(max_length=200, verbose_name='Size'),
        ),
    ]
