# Generated by Django 4.1.3 on 2022-11-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='static/def.jpg', null=True, upload_to='media/banner', verbose_name='Image of Banner')),
                ('title', models.ForeignKey(blank=True, default='New Wear', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.product')),
            ],
        ),
    ]
